FROM pytorch/pytorch:2.10.0-cuda13.0-cudnn9-devel@sha256:48af19ebb88034e0325decc2b6142e5b9bfc276eaa5197ab6d94582f1d78ea4c
# This base image has pre-installed:
# - python 3.12.3
# - CUDA 13.0 + dev toolkit
# - torch 2.10.0
WORKDIR /app
# Set env vars
ENV UV_COMPILE_BYTECODE=1 \
    UV_TORCH_BACKEND=cu130 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/app/.venv \
    TRITON_CACHE_DIR=/tmp/triton_cache \
    TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_cache
# Install dependencies; mount in cache/uv files to avoid extra copy layer; force pre-built wheels to match container runtime for flash-attn
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --no-install-project --all-groups --all-extras && \
    uv pip install "flash-attn @ https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.7.16/flash_attn-2.8.3%2Bcu130torch2.10-cp312-cp312-linux_x86_64.whl"
# Activate uv venv
ENV PATH="/app/.venv/bin:$PATH"
# Copy sources
ADD . .
# Entrypoint
CMD ["python3", "main.py"]
