# lightning.pytorch==2.0.0
seed_everything: 153201820 # For reproducibility
trainer:
  accelerator: "gpu"
  default_root_dir: "./checkpoints"
  accumulate_grad_batches: 128
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        name: "gecco-large"
        project: "gecco"
        log_model: true
  max_epochs: 4
  log_every_n_steps: 1
  gradient_clip_val: 1.0
model:
  class_path: bertblocks.training.modules.BertBlocksPretrainingModule
  init_args:
    objective: "diffusion"
    learning_rate: 5e-4
    weight_decay: 1e-6
    compile_model: true
    optimizer_class: "adamw"
    scheduler_warmup_kind: "linear"
    scheduler_warmup_steps: 2000
    scheduler_warmup_decay: 0.01
    scheduler_training_kind: "constant"
    scheduler_training_steps: -1
    scheduler_training_decay: 1.0
    scheduler_cooldown_kind: "linear"
    scheduler_cooldown_steps: 0
    scheduler_cooldown_decay: 0.1
    pretrained_tokenizer_name_or_path: ${data.init_args.pretrained_tokenizer_name_or_path}
    model_config_kwargs:
      actv_fn: "gelu"
      add_token_type_emb: false
      attn_implementation: "flash_attention_2"
      unpadding: true
      attn_out_bias: true
      attn_proj_bias: true
      attn_dropout_prob: 0.1
      classifier_dropout: 0.0
      emb_dropout_prob: 0.0
      hidden_dropout_prob: 0.0
      hidden_size: 1024
      include_final_norm: false
      initializer_cutoff_factor: 4.0
      initializer_gain: 1.0
      initializer_kind: "trunc_normal"
      initializer_range: 0.02
      intermediate_size: 4096
      mlp_in_bias: false
      mlp_out_bias: false
      mlp_type: "glu"
      norm_bias: false
      norm_eps: 1e-12
      norm_fn: "rms"
      norm_kind: "pre"
      num_attention_heads: 16
      num_blocks: 28
      pad_token_id: 0
      mask_token_id: 103
      pos_emb_kind: "alibi"
      vocab_size: 28996
      head_type: "glu"
      max_sequence_length: ${data.init_args.max_sequence_length}
data:
  class_path: bertblocks.training.modules.BertBlocksPretrainingDataModule
  init_args:
    pretrained_tokenizer_name_or_path: "bert-base-uncased"
    objective: "diffusion"
    dataset_name_or_path: "/mnt/ceph/storage/data-in-progress/data-research/large-language-models/colm25-modern-german-encoder/fineweb-2/data/deu_Latn/"
    file_format: "parquet"
    shuffle: false
    collator_kwargs:
      num_steps: 256
      sampling_eps: 1e-3
      mask_token_id: 103
    max_sequence_length: 1024
    train_batch_size: 32
    val_batch_size: 32
    num_workers: 8
