# lightning.pytorch==2.0.0
seed_everything: 153201820 # For reproducibility
trainer:
  accelerator: "gpu"
  precision: "transformer-engine"
  default_root_dir: "./checkpoints"
  #logger:
  #  - class_path: lightning.pytorch.loggers.WandbLogger
  #    init_args:
  #      project: "<project_name>"
  #      entity: "<username>"
  #      log_model: false
  max_epochs: 1
  log_every_n_steps: 1
model:
  class_path: bertblocks.training.modules.BertBlocksPretrainingModule
  init_args:
    optimizer_class: "adamw"
    optimizer_quantized: true
    learning_rate: 1e-4
    weight_decay: 1e-5
    scheduler_warmup_steps: 1000
    scheduler_warmup_decay: 0.1
    pretrained_tokenizer_name_or_path: ${data.init_args.pretrained_tokenizer_name_or_path}
    compile_model: true
    model_config_kwargs:
      hidden_size: 512
      num_blocks: 6
      num_attention_heads: 4
      intermediate_size: 2048
      actv_fn: "silu"
      norm_kind: "pre"
      norm_fn: "rms"
      block_pos_enc_kind: "alibi"
      max_sequence_length: ${data.init_args.max_sequence_length}
    objective: ${data.init_args.objective}
data:
  class_path: bertblocks.training.modules.BertBlocksPretrainingDataModule
  init_args:
    objective: mlm
    dataset_name_or_path: roneneldan/TinyStories
    pretrained_tokenizer_name_or_path: "bert-base-uncased"
    max_sequence_length: 512
    train_batch_size: 16
    val_batch_size: 16
    num_workers: 1
